version: "2.2.1"  # optional since v1.27.0
services:

  nginx:
    image: xusai2014/nginx-proxy:latest
    mem_limit: 512m
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/data/https-file:/root/https-file
    links:
      - video:localhost
      - www:localhost
      - api_service:localhost
    depends_on:
      - mongodb
      - www
      - api_service
  mongodb:
    image: mongo:5.0.5
    mem_limit: 1024m
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /root/data/db:/data/db
  www:
    image: xusai2014/www
    mem_limit: 512m
    ports:
      - "3000:80"
    links:
      - mongodb:localhost
    depends_on:
      - mongodb
  api_service:
    image: xusai2014/api-service
    mem_limit: 512m
    ports:
      - "3003:80"
    volumes:
      - /root/data/weixin:/root/weixin
    links:
      - mongodb:localhost
    depends_on:
      - mongodb
  video:
    image: xusai2014/music-video
    mem_limit: 512m
    ports:
      - "3004:80"
    links:
      - mongodb:localhost
    depends_on:
      - mongodb

volumes:
  logvolume01: {}