services:
  mongodb:
    image: mongo:5.0.5
    mem_limit: 512m
    cpus: 0.25
    restart: always
    ports:
      - "27017"
    volumes:
      - ./data/db:/data/db
  www:
    image: xusai2014/www
    mem_limit: 256m
    ports:
      - "3000:80"
    links:
      - mongodb:localhost
    depends_on:
      - mongodb
  api_service:
    image: xusai2014/api-service
    mem_limit: 512m
    cpus: 0.25
    ports:
      - "3003:80"
    volumes:
      - ./data/weixin:/root/weixin
    links:
      - mongodb:localhost
    depends_on:
      - mongodb
  prometheus:
    image: prom/prometheus
    ports:
      - "3007:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - '9100'
  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana_data:/varlib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    ports:
      - '3009:3000'
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    command:
      -nginx.scrape-uri
      -http://nginx:8080/stub_status
    depends_on:
      - prometheus
    ports:
      - '9113'
volumes:
  logvolume01: {}
