version: "2.2.1"  # optional since v1.27.0
services:
  nginx:
    image: xusai2014/nginx-proxy:latest
    mem_limit: 256m
    ports:
      - "80:80"
      - "443:443"
      - "8080"
    volumes:
      - /root/data/https-file:/root/https-file
    links:
      - video:localhost
      - www:localhost
      - api_service:localhost
      - grafana:localhost
      - prometheus:localhost
      - node-exporter:localhost
    depends_on:
      - mongodb
      - www
      - api_service
      - useweb3
      - grafana
      - prometheus
      - node-exporter
  mongodb:
    image: mongo:5.0.5
    mem_limit: 512m
    cpus: 0.25
    restart: always
    ports:
      - "27017"
    volumes:
      - /root/data/db:/data/db
  www:
    image: xusai2014/www
    mem_limit: 256m
    ports:
      - "80"
    links:
      - mongodb:localhost
    depends_on:
      - mongodb
  api_service:
    image: xusai2014/api-service
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M
    ports:
      - "80"
    volumes:
      - /root/data/weixin:/root/weixin
    links:
      - mongodb:localhost
    depends_on:
      - mongodb
#  video:
#    image: xusai2014/music-video
#    mem_limit: 256m
#    ports:
#      - "80"
#    links:
#      - mongodb:localhost
#    depends_on:
#      - mongodb
  useweb3:
    image: xusai2014/useweb3
    mem_limit: 256m
    ports:
      - "80"
    volumes:
      - /root/data/useweb3/.env.local:/app/.env.local
  web3_info:
    image: xusai2014/web3info
    mem_limit: 256m
    ports:
      - "80"
    links:
      - mongodb:localhost
    depends_on:
      - mongodb
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090"
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#  node-exporter:
#    container_name: node-exporter
#    image: prom/node-exporter
#    ports:
#      - '9100'
#  grafana:
#    image: grafana/grafana
#    volumes:
#      - /root/data/grafana_data:/varlib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=pass
#    depends_on:
#      - prometheus
#    ports:
#      - '3000'
#  nginx-exporter:
#    container_name: nginx-exporter
#    image: nginx/nginx-prometheus-exporter
#    links:
#      - nginx:localhost
#    depends_on:
#      - nginx
#    command:
#      - "-nginx.scrape-uri=http://nginx:8080/stub_status"
#    ports:
#      - '9113'
volumes:
  logvolume01: {}
