version: "3.9"  # optional since v1.27.0
services:
  nginx:
    build:
      context: ./nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/https-file:/root/https-file
    links:
      - video:localhost
      - www:localhost
      - api_service:localhost
    depends_on:
      - mongodb
      - www
      - api_service
  mongodb:
    image: mongo:5.0.5
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  video:
    build:
      context: ./music-video
    ports:
      - "6000:80"
    links:
      - mongodb:localhost
    depends_on:
      - mongodb
  www:
    build:
      context: ./TalkCar
    ports:
      - "3000:80"
    links:
      - mongodb:localhost
    depends_on:
      - mongodb
  api_service:
    build:
      context: ./PublicShare
    ports:
      - "4000:80"
    links:
      - mongodb:localhost
    depends_on:
      - mongodb
volumes:
  logvolume01: {}