version: "3.9"  # optional since v1.27.0
services:
  nginx:
    image: xusai2014/nginx-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/https-file:/root/https-file
    links:
      - video:localhost
      - www:localhost
      - api-service:localhost
    depends_on:
      - mongodb
      - www
      - api-service
  mongodb:
    image: mongo:5.0.5
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db

  video:
    image: xusai2014/music-video
    ports:
      - "5000:80"
    links:
      - mongodb:localhost
    depends_on:
      - mongodb
  www:
    image: xusai2014/www
    ports:
      - "3000:80"
    links:
      - mongodb:localhost
    depends_on:
      - mongodb
  api-service:
    image: xusai2014/api-service
    ports:
      - "4000:80"
    links:
      - mongodb:localhost
    depends_on:
      - mongodb
volumes:
  logvolume01: {}