global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:3007'
  - job_name: 'node'
    static_configs:
      - targets:
          - 'node-exporter:3008'
