global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: 'node'
    static_configs:
      - targets:
          - 'node-exporter:9100'
  - job_name: 'docker'
    static_configs:
      - targets:
          - 'host.docker.internal:9323'
  - job_name: 'nginx_exporter'
    static_configs:
      - targets:
          - 'nginx-exporter:9113'
